apiVersion: v1
kind: Template
metadata:
  name: in-place-upgrades-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: upgrades
    spec:
      envName: ${ENV_NAME}
      title: Upgrades
      deploymentRepo: TBD
      frontend:
        paths:
          - /apps/upgrades
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
      - appId: upgrades
        title: Upgrades
        href: "/insights/upgrades"
      module:
        manifestLocation: "/apps/upgrades/fed-mods.json"
        modules:
          - id: "upgrades"
            module: "./RootApp"
            routes:
            - pathname: "/insights/upgrades"

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: TBD
